/* eslint-disable */
/**
 * Generated API.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@0.14.1.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type { ApiFromModules } from "convex/api";
import type * as createRace from "../createRace";
import type * as createText from "../createText";
import type * as deleteColumn from "../deleteColumn";
import type * as endStanding from "../endStanding";
import type * as incrementCounter from "../incrementCounter";
import type * as lib_helpers from "../lib/helpers";
import type * as listTexts from "../listTexts";
import type * as listTypes from "../listTypes";
import type * as readRace from "../readRace";
import type * as readStanding from "../readStanding";
import type * as readText from "../readText";
import type * as storeUser from "../storeUser";
import type * as tug_createTug from "../tug/createTug";
import type * as tug_decrementTimer from "../tug/decrementTimer";
import type * as tug_joinTug from "../tug/joinTug";
import type * as tug_readTug from "../tug/readTug";
import type * as tug_updatePosition from "../tug/updatePosition";
import type * as user_readRaces from "../user/readRaces";
import type * as user_readTugs from "../user/readTugs";
import type * as user_readUser from "../user/readUser";
import type * as withUser from "../withUser";

/**
 * A type describing your app's public Convex API.
 *
 * This `API` type includes information about the arguments and return
 * types of your app's query and mutation functions.
 *
 * This type should be used with type-parameterized classes like
 * `ConvexReactClient` to create app-specific types.
 */
export type API = ApiFromModules<{
  createRace: typeof createRace;
  createText: typeof createText;
  deleteColumn: typeof deleteColumn;
  endStanding: typeof endStanding;
  incrementCounter: typeof incrementCounter;
  "lib/helpers": typeof lib_helpers;
  listTexts: typeof listTexts;
  listTypes: typeof listTypes;
  readRace: typeof readRace;
  readStanding: typeof readStanding;
  readText: typeof readText;
  storeUser: typeof storeUser;
  "tug/createTug": typeof tug_createTug;
  "tug/decrementTimer": typeof tug_decrementTimer;
  "tug/joinTug": typeof tug_joinTug;
  "tug/readTug": typeof tug_readTug;
  "tug/updatePosition": typeof tug_updatePosition;
  "user/readRaces": typeof user_readRaces;
  "user/readTugs": typeof user_readTugs;
  "user/readUser": typeof user_readUser;
  withUser: typeof withUser;
}>;
