import Head from "next/head";
import Image from "next/image";
import { Container } from "reactstrap";
import styles from "../styles/Home.module.css";

export default function About() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Meet the Developers</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <p>Tug of War Typeracer was pioneered by Lower Moreland High School's Coding Club...</p>
                <section>
                    <h1 className="text-center">Meet the Developers behind the Game</h1>
                    <Container className="d-flex flex-wrap">
                        <figure className="w-200 mx-3">
                            <Image src="/jason-nagel.jpg" width={100} height={100} />
                            <figcaption>Jason Nagel, Backend Developer</figcaption>
                        </figure>

                        <figure className="w-200 mx-3">
                            <Image src="/jason-nagel.jpg" width={100} height={100} />
                            <figcaption>Aaron Schacter, Backend Developer</figcaption>
                        </figure>
                        <figure className="w-200 mx-3">
                            <Image src="/jason-nagel.jpg" width={100} height={100} />
                            <p>Alan Joseph, Backend Developer</p>
                        </figure>
                        <figure className="w-200 mx-3">
                            <Image src="/jason-nagel.jpg" width={100} height={100} />
                            <p>Varun Singh, Lead Developer</p>
                        </figure>
                        <figure className="w-200 mx-3">
                            <Image src="/jason-nagel.jpg" width={100} height={100} />
                            <p>Ho Lam Zhang, Backend Developer</p>
                        </figure>
                        <figure className="w-200">
                            <Image src="/jason-nagel.jpg" width={100} height={100} />
                            <figcaption>Phillip Duarte, Frontend Developer</figcaption>
                        </figure>
                    </Container>

                </section>
            </main>
        </div>
    );
}