import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import { useMutation } from '../convex/_generated/react'
import styles from '../styles/Home.module.css'

const Home = () => {
  const createRace = useMutation('createRace');
  const createTug = useMutation('createTug');
  const router = useRouter();

  return (
    <div className={styles.container}>
      <Head>
        <title>Tug of War Typeracer | LMHS Coding Club</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to LMHS Coding Club's <a href="https://tugoftype.lmhscodingclub.com">Tug of Type</a>
        </h1>

        <p className={styles.description}>
          <button onClick={async () => {
            const id = await createRace();
            router.push(`/race?id=${id}`);
          }}>
            Create a Race
          </button>
          <button onClick={async () => {
            const id = await createTug();
            router.push(`/tug?id=${id}`)
          }}>Create a Tug</button>
        </p>

      </main>
    </div>
  )
}

export default Home
